name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:

  tests:
    strategy:
      matrix:
        container: [2024-06-24-aiida2.4.0-py3.11.0,
                    2024-06-24-aiida2.4.1-py3.11.0,
                    2024-06-24-aiida2.4.2-py3.11.0,
                    2024-06-24-aiida2.5.0-py3.11.0,
                    2024-06-24-aiida2.5.1-py3.11.0,
                    2024-06-24-aiida2.5.2-py3.11.0]
        amber: [23.6=nompi_py311he003265_102]
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
        image: harbor.stfc.ac.uk/biosimulation-cloud/aiida-testbase:${{ matrix.container }}
    name: ${{ matrix.container }}-amber${{ matrix.amber }}
    steps:
    - uses: actions/checkout@v4

    - name: install AmberTools
      shell: bash
      run: mamba install ambertools=${{ matrix.amber }} -c conda-forge -yq

    - name: Start AiiDA with a test profile
      shell: bash
      run: /home/aiida/aiida-start

    - name: Install aiida-amber and its testing dependencies
      shell: bash
      run: pip install -e .[testing]

    - name: Run test suite
      shell: bash
      run: pytest -s --cov aiida_amber --cov-report term-missing --cov-append .

    - name: Report Coverage
      uses: coverallsapp/github-action@v2

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[docs]
    - name: Build docs
      run: cd docs && make

  pre-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[pre-commit,docs,testing]
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
